# Generated by Django 5.2.1 on 2025-11-24 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EDITAR_MASCOTA', 'Solicitud de edición de mascota'), ('ELIMINAR_MASCOTA', 'Solicitud de eliminación de mascota'), ('PROBLEMA_TECNICO', 'Reportar problema técnico'), ('CONSULTA_GENERAL', 'Consulta general'), ('CAMBIO_DATOS', 'Solicitud de cambio de datos personales'), ('REPORTE_USUARIO', 'Reportar comportamiento de usuario'), ('SUGERENCIA', 'Sugerencia de mejora'), ('OTRO', 'Otro tipo de solicitud')], help_text='Tipo de solicitud', max_length=30)),
                ('asunto', models.CharField(help_text='Asunto o título de la solicitud', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('RESUELTA', 'Resuelta'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', help_text='Prioridad asignada por el administrador', max_length=10)),
                ('respuesta_admin', models.TextField(blank=True, help_text='Respuesta del administrador')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto (opcional)', null=True, upload_to='solicitudes/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('mascota', models.ForeignKey(blank=True, help_text='Mascota relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='mascota.mascota')),
                ('usuario', models.ForeignKey(help_text='Usuario que realiza la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='solicitudes_usuario_aaca94_idx'), models.Index(fields=['estado', 'prioridad'], name='solicitudes_estado_a841cd_idx'), models.Index(fields=['creada_en'], name='solicitudes_creada__a9802e_idx')],
            },
        ),
    ]
