# Generated by Django 5.2.1 on 2025-10-27 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        ('mascota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la cita (timezone-aware).')),
                ('motivo', models.CharField(help_text='Motivo breve de la cita.', max_length=160)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(blank=True, help_text='Clínica donde se atenderá. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinicas.clinica')),
                ('dueno', models.ForeignKey(help_text='Usuario dueño que crea/posee la cita.', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascota.mascota')),
                ('veterinario', models.ForeignKey(blank=True, help_text='Usuario veterinario asignado (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
                'indexes': [models.Index(fields=['dueno', 'fecha_hora'], name='citas_cita_dueno_i_c8e190_idx'), models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx')],
            },
        ),
    ]
