# Generated by Django 5.2.1 on 2025-11-10 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinicas.clinica'),
        ),
    ]
