# Generated by Django 5.2.1 on 2025-11-02 18:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACUNA', 'Vacuna'), ('CONTROL', 'Control'), ('TRATAMIENTO', 'Tratamiento'), ('CIRUGIA', 'Cirugía'), ('OTRO', 'Otro')], default='CONTROL', max_length=16)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que ocurrió el evento.')),
                ('titulo', models.CharField(help_text="Título corto: 'Vacuna Rabia', 'Control anual', etc.", max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, help_text='Opcional: adjuntar documento (PDF, imagen, etc.).', null=True, upload_to='historial_adjuntos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(help_text='Mascota a la que corresponde el evento.', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='mascota.mascota')),
                ('veterinario', models.ForeignKey(blank=True, help_text='Usuario veterinario que realizó/registró el evento (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['mascota', 'fecha'], name='historial_e_mascota_f11c2b_idx'), models.Index(fields=['tipo'], name='historial_e_tipo_6a443a_idx')],
            },
        ),
    ]
