# Generated by Django 5.2.1 on 2025-10-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DUENO', 'Dueño de mascota'), ('VET', 'Veterinario')], default='DUENO', max_length=10)),
                ('vet_estado', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=10, null=True)),
                ('vet_registro', models.CharField(blank=True, help_text='Número de registro profesional (SEREMI/colegiatura, etc.)', max_length=100)),
                ('vet_clinica', models.CharField(blank=True, help_text='Clínica/centro donde ejerces', max_length=200)),
                ('vet_observaciones', models.TextField(blank=True, help_text='Notas internas (solo admin)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
