# Generated by Django 5.2.1 on 2025-11-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='licencia_medica',
            field=models.FileField(blank=True, help_text='Documento obligatorio para veterinarios (PDF/JPG/PNG)', null=True, upload_to='licencias_vets/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vet_clinica',
            field=models.CharField(blank=True, help_text='Clínica o centro donde ejerce', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vet_estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vet_observaciones',
            field=models.TextField(blank=True, help_text='Notas internas visibles solo para el administrador'),
        ),
    ]
