# Generated by Django 5.2.1 on 2025-11-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_perfil_licencia_medica_alter_perfil_vet_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='vet_rut',
            field=models.CharField(blank=True, help_text='RUT del veterinario (formato: 12.345.678-9)', max_length=12),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='licencia_medica',
            field=models.FileField(blank=True, help_text='Título de médico veterinario (PDF/JPG/PNG)', null=True, upload_to='licencias_vets/'),
        ),
    ]
