# Generated by Django 5.2.1 on 2025-12-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_perfil_vet_rut_alter_perfil_licencia_medica'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vet_clinica',
            field=models.CharField(blank=True, help_text='Clínica o centro donde ejerce (opcional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vet_registro',
            field=models.CharField(blank=True, help_text='RUN (Rol Único Nacional del veterinario)', max_length=100),
        ),
    ]
